random-number:
  url: http://127.0.0.1:9000

spring:
  application:
    name: fibonacci-microservice
springdoc:
  api-docs:
    path: /fibonacci/fibonacci-docs
  swagger-ui:
    path: /fibonacci/doc/
server:
  port: 8400
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka