plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'jacoco'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group 'com.cedaniel200.microservices'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jacoco {
    toolVersion = "0.8.11"
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven{
        url 'https://maven.aliyun.com/nexus/content/groups/public/'
    }
}

ext {
    set('springCloudVersion', "2023.0.3")

    okhttpVersion = '4.12.0'
    retrofitVersion = '2.11.0'

    restAssureVersion = '5.5.0'
    wiremockVersion = '3.9.1'

    openapiUIVersion = '2.6.0'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation "com.squareup.okhttp3:okhttp:${okhttpVersion}"
    implementation "com.squareup.retrofit2:retrofit:${retrofitVersion}"
    implementation "com.squareup.retrofit2:converter-gson:${retrofitVersion}"

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${openapiUIVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "io.rest-assured:rest-assured:${restAssureVersion}"
    testImplementation "io.rest-assured:xml-path"
    testImplementation "org.wiremock:wiremock-standalone:${wiremockVersion}"

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

test {
    useJUnitPlatform()
}
