spring:
  application:
    name: add-microservice
springdoc:
  api-docs:
    path: /add-docs
  swagger-ui:
    path: /add.html
server:
  port: 8200
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka